root: true

env:
  node: true
  es2021: true
  jest: true

plugins:
  - fp

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  fp/no-mutating-methods: error
  fp/no-let: error
  no-console: off

  # ESM en Node no usa extensiones en imports locales
  import/extensions:
    - error
    - ignorePackages
    - js: always

overrides:
  - files:
      - '**/__tests__/**/*.js'
    rules:
      no-underscore-dangle: off
